# Generated by Django 5.2.2 on 2025-06-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('documentonro', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentasCobrar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=100)),
                ('tablaid', models.IntegerField()),
                ('cuota', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=5, max_digits=18)),
                ('cobrado', models.DecimalField(decimal_places=5, max_digits=18)),
                ('vence', models.DateTimeField()),
            ],
            options={
                'db_table': 'cuentas_cobrar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depositos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('deposito', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'depositos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('moneda', models.CharField(max_length=50)),
                ('abrebiatura', models.CharField(max_length=5)),
                ('decimales', models.IntegerField()),
                ('activo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'monedas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlazoDetalles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuota', models.IntegerField()),
                ('dias', models.IntegerField()),
            ],
            options={
                'db_table': 'plazo_detalles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plazos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plazo', models.CharField(max_length=100)),
                ('tipoid', models.IntegerField()),
                ('cuotas', models.IntegerField()),
                ('irregular', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'plazos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TalonarioDetalle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=100)),
                ('tablaid', models.IntegerField()),
                ('talonarionro', models.IntegerField()),
            ],
            options={
                'db_table': 'talonario_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talonarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nroinicial', models.IntegerField()),
                ('nrofinal', models.IntegerField()),
                ('seriea', models.CharField(max_length=5)),
                ('serieb', models.CharField(max_length=5)),
                ('timbrado', models.CharField(max_length=15)),
                ('vigenciaincio', models.DateField()),
                ('vigenciafin', models.DateField()),
                ('activo', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'talonarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('abrebiatura', models.CharField(max_length=5)),
                ('tipoid', models.IntegerField()),
                ('activo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tipos_documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaproceso', models.DateTimeField(blank=True, null=True)),
                ('fechafactura', models.DateTimeField(blank=True, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('nrofactura', models.IntegerField()),
                ('totalexento', models.DecimalField(decimal_places=5, max_digits=18)),
                ('totalimpuesto', models.DecimalField(decimal_places=5, max_digits=18)),
                ('totalbase', models.DecimalField(decimal_places=5, max_digits=18)),
                ('totalfactura', models.DecimalField(decimal_places=5, max_digits=18)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
